let
  feature = "starship-quickshell";
in
{
  self,
  inputs,
  ...
}:
{
  flake.modules.homeManager.${feature} =
    {
      pkgs,
      lib,
      config,
      ...
    }:
    let
      # Reads CPU/mem/disk/network/temperature and emits JSON for the HUD.
      starshipStats = pkgs.writeShellScriptBin "starship-stats" ''
        # shellcheck disable=SC1091
        set -u

        sample_cpu() {
          awk '/^cpu /{total=0; for(i=2;i<=NF;i++) total+=$i; idle=$5; print total, idle}' /proc/stat
        }

        sample_net() {
          awk 'NR>2 {
            if ($1 ~ /:$/) {
              gsub(":", "", $1)
              if ($1 != "lo") { rx += $2; tx += $10 }
            }
          } END { print rx, tx }' /proc/net/dev
        }

        read -r C1_TOTAL C1_IDLE < <(sample_cpu)
        read -r N1_RX N1_TX < <(sample_net)
        sleep 1
        read -r C2_TOTAL C2_IDLE < <(sample_cpu)
        read -r N2_RX N2_TX < <(sample_net)

        # CPU percent over the sample window
        CPU_DT=$(( C2_TOTAL - C1_TOTAL ))
        CPU_IDLE_DT=$(( C2_IDLE - C1_IDLE ))
        CPU=0
        if [ "$CPU_DT" -gt 0 ]; then
          CPU=$(( (CPU_DT - CPU_IDLE_DT) * 100 / CPU_DT ))
        fi

        # Memory percent
        read -r MEM_TOTAL < <(awk '/^MemTotal:/{print $2}' /proc/meminfo)
        read -r MEM_AVAIL < <(awk '/^MemAvailable:/{print $2}' /proc/meminfo)
        MEM=0
        if [ "$MEM_TOTAL" -gt 0 ]; then
          MEM=$(( (MEM_TOTAL - MEM_AVAIL) * 100 / MEM_TOTAL ))
        fi

        # Root filesystem usage
        DISK=$(${pkgs.coreutils}/bin/df -P / | awk 'NR==2 {gsub("%","",$5); print $5}')
        [ -z "$DISK" ] && DISK=0

        # Network rate in KB/s
        NET_RX=$(( (N2_RX - N1_RX) / 1024 ))
        NET_TX=$(( (N2_TX - N1_TX) / 1024 ))
        [ "$NET_RX" -lt 0 ] && NET_RX=0
        [ "$NET_TX" -lt 0 ] && NET_TX=0

        # Temperature (millidegrees -> degrees)
        TEMP=0
        if [ -r /sys/class/thermal/thermal_zone0/temp ]; then
          TEMP=$(( $(cat /sys/class/thermal/thermal_zone0/temp) / 1000 ))
        fi

        ${pkgs.jq}/bin/jq -nc \
          --arg cpu "$CPU" \
          --arg mem "$MEM" \
          --arg disk "$DISK" \
          --arg netrx "$NET_RX" \
          --arg nettx "$NET_TX" \
          --arg temp "$TEMP" \
          '{cpu: $cpu, mem: $mem, disk: $disk, netrx: $netrx, nettx: $nettx, temp: $temp}'
      '';

      # A JS palette file that the QML can import (import "colors.js" as Colors).
      colorsJs =
        let
          inherit (config.lib.stylix.colors.withHashtag)
            base00
            base01
            base02
            base03
            base04
            base05
            base06
            base07
            base08
            base09
            base0A
            base0B
            base0C
            base0D
            base0E
            base0F
            ;
        in
        ''
          // Generated from the active Stylix base16 scheme.
          var base00 = "${base00}";
          var base01 = "${base01}";
          var base02 = "${base02}";
          var base03 = "${base03}";
          var base04 = "${base04}";
          var base05 = "${base05}";
          var base06 = "${base06}";
          var base07 = "${base07}";
          var base08 = "${base08}";
          var base09 = "${base09}";
          var base0A = "${base0A}";
          var base0B = "${base0B}";
          var base0C = "${base0C}";
          var base0D = "${base0D}";
          var base0E = "${base0E}";
          var base0F = "${base0F}";
          var fontFamily = "${config.stylix.fonts.monospace.name}";
        '';

      # Paths to the tools used by the QML, as a JS module.
      pathsJs = ''
        // Generated by the starship-quickshell module.
        var hyprctl = "${pkgs.hyprland}/bin/hyprctl";
        var wpctl = "${pkgs.wireplumber}/bin/wpctl";
        var brightnessctl = "${pkgs.brightnessctl}/bin/brightnessctl";
        var stats = "${starshipStats}/bin/starship-stats";
        var face = "${config.home.homeDirectory}/.face";
        var userName = "${config.home.username}";
      '';
    in
    {
      home.packages = with pkgs; [
        quickshell
        brightnessctl
        wireplumber
        starshipStats
      ];

      xdg.configFile = {
        "quickshell/shell.qml".source = ./shell.qml;
        "quickshell/colors.js".text = colorsJs;
        "quickshell/paths.js".text = pathsJs;
        "quickshell/components/WorkspaceButton.qml".source = ./components/WorkspaceButton.qml;
        "quickshell/components/StatBlock.qml".source = ./components/StatBlock.qml;
        "quickshell/components/HudSlider.qml".source = ./components/HudSlider.qml;
        "quickshell/components/UserBadge.qml".source = ./components/UserBadge.qml;
      };

      systemd.user.services.quickshell = {
        Unit = {
          Description = "Starship Holographic HUD (Quickshell)";
          After = [ "graphical-session.target" ];
          PartOf = [ "graphical-session.target" ];
        };
        Service = {
          ExecStart = "${pkgs.quickshell}/bin/quickshell -p ${config.xdg.configHome}/quickshell";
          Restart = "on-failure";
          RestartSec = 2;
        };
        Install = {
          WantedBy = [ "graphical-session.target" ];
        };
      };
    };
}
